version: '2'
services:
    suchazapis-app:
        image: suchazapis
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://suchazapis-mysql:3306/suchazapis?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    suchazapis-mysql:
        extends:
            file: mysql.yml
            service: suchazapis-mysql
